apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argo
  labels:
    cluster: c0
    app: argocd
spec:
  project: default
  destination:
    name: in-cluster
    namespace: argo
  source:
    repoURL: https://gitlab.com/tomkukral/training-model.git
    targetRevision: HEAD
    path: argo/cd
  syncPolicy:
    syncOptions:
    - Validate=true
    - CreateNamespace=true
