apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kad
  namespace: argo
spec:
  project: default
  destination:
    namespace: kad
    server: in-cluster
  source:
    path: helm
    repoURL: https://gitlab.com/6shore.net/kad.git
    targetRevision: HEAD
    helm:
      parameters:
      - name: replicas
        value: "2"
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
