apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kad
  namespace: argo
spec:
  project: default
  destination:
    namespace: kad
    name: in-cluster
    # server: https://kubernetes.default.svc
  source:
    path: helm
    repoURL: https://gitlab.com/6shore.net/kad.git
    targetRevision: HEAD
    helm:
      parameters:
      - name: replicas
        value: "2"
      - name: ingress.enabled
        value: "true"
      - name: cluster
        value: "c0"
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
