apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://gitlab.com/tomkukral/training-model.git
    targetRevision: HEAD
    path: loki
  destination:
    name: https://kubernetes.default.svc
    namespace: loki
  syncPolicy:
    syncOptions:
    - Validate=true
    - CreateNamespace=true
