apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argo
spec:
  destination:
    namespace: minio
    server: https://kubernetes.default.svc
  project: default
  source:
    path: minio
    repoURL: https://gitlab.com/tomkukral/training-model.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
